export const FLIP_ANIMATION_DURATION = 1000

export const FLIP_DELAY_BETWEEN_TILE = 150

export const FUll_FLIP_WAIT = FLIP_ANIMATION_DURATION + (FLIP_DELAY_BETWEEN_TILE * 4)

export const BOUNCE_DELAY_BETWEEN_TILE = 150

export const INVALID_WAIT = 300 
