const FLIP_ANIMATION_DURATION = 1000

export const FLIP_TILE_DELAY = 150

export const FUll_FLIP_WAIT = FLIP_ANIMATION_DURATION + (FLIP_TILE_DELAY * 4)

export const BOUNCE_TILE_DELAY = 150

export const INVALID_WAIT = 300 
